name: Auto-merge Setup

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - development

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.base_ref == 'development' # Double check we're merging to development
    steps:
      - name: Enable auto-merge
        run: |
          gh pr merge "$PR_URL" --auto --merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
